### ISSUE TITLE
list-dhcpd-leases script missing

### ISSUE THREAD

**Issue by casr** [northox/openbsd-apu2#2]
I could not find the `list-dhcpd-leases` script that is being used for `update-webpage` so I wrote this simple script to fill the gap for now:

```sh
#!/bin/sh

cat /var/db/dhcpd.leases | \
  sed -n \
    -e 's/.*lease \([0-9.]*\).*/\1/p' \
    -e 's/.*hardware ethernet \([0-9a-f:]*\).*/\1/p' \
    -e 's/.*client-hostname \("[^"]*"\).*/\1/p' | \
  paste -d "\t" - - - | sort | uniq | column -t
```

Probably pretty dumb as I have not tested it on much input at all.

Posting here as I thought it could be useful for others. By the way, thank you for assembling all this information!

**Comment by northox** [comment]
Appreciated! Totally forgot avout that. I'll post mine, even though its pretty crude too and let's see what's best.

**Comment by northox** [comment]
Hey @casr 

I found bugs in both your and my version and finally came up with this. Tell me if everything’s fine on your end.

```sh
#!/bin/sh
awk '/{/{if(x)print x;x=""}{gsub(";","");x=(!x)?$0:x" "$0}END{print x}' /var/db/dhcpd.leases | \
sed -E -n -e 's/lease ([0-9.]+).*ethernet ([0-9a-f:]+)(.*hostname "([^"]*)" }|.*([^hostname].)* })/\1 \2 \4/p' | \
sort -u | column -t
```

See 1a59f22597f1ed2f722f5451152565e61c78710b

**Comment by casr** [comment]
Yes, this works a lot better than my version!
